# Generated by Django 5.2 on 2025-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=False)),
                ('document_joint', models.FileField(blank=True, null=True, upload_to='dossiers/%Y/%m/%d/')),
                ('livrer', models.BooleanField(default=False)),
                ('support_pdf', models.FileField(blank=True, null=True, upload_to='dossiers/memoires/')),
            ],
        ),
    ]
