# Generated by Django 5.2 on 2025-06-14 14:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('AUDIT ET CONTRÔLE DE GESTION - (ACG)', 'AUDIT ET CONTRÔLE DE GESTION - (ACG)'), ('ADMINISTRATION DES AFFAIRES - (ADAF)', 'ADMINISTRATION DES AFFAIRES - (ADAF)'), ('ANGLAIS - (ANG)', 'ANGLAIS - (ANG)'), ('SCIENCE JURIDIQUE OPTION DROIT PRIVE - (SCJ-PV)', 'SCIENCE JURIDIQUE OPTION DROIT PRIVE - (SCJ-PV)'), ('SCIENCE JURIDIQUE OPTION DROIT PUBLIC - (SCJ-PB)', 'SCIENCE JURIDIQUE OPTION DROIT PUBLIC - (SCJ-PB)'), ('FINANCE BANQUE ASSURANCE - (FBA)', 'FINANCE BANQUE ASSURANCE - (FBA)'), ('FINANCE COMPTABILITE ET GESTION DES ENTREPRISES - (FCGE)', 'FINANCE COMPTABILITE ET GESTION DES ENTREPRISES - (FCGE)'), ('GENIE CIVIL OPTION BATIMENT - (GBAT)', 'GENIE CIVIL OPTION BATIMENT - (GBAT)'), ('GENIE CIVIL OPTION TRAVAUX PUBLIC - (GTP)', 'GENIE CIVIL OPTION TRAVAUX PUBLIC - (GTP)'), ('GESTION DES RESSOURCES HUMAINE - (GRH)', 'GESTION DES RESSOURCES HUMAINE - (GRH)'), ('INFORMATIQUE OPTION GENIE LOGICIEL - (IGL)', 'INFORMATIQUE OPTION GENIE LOGICIEL - (IGL)'), ('LETTRES MODERNES - (LMO)', 'LETTRES MODERNES - (LMO)'), ('MARKETING MANAGEMENT - (MAM)', 'MARKETING MANAGEMENT - (MAM)'), ('MINE GEOLOGIE ET PETRÔLE - (MGP)', 'MINE GEOLOGIE ET PETRÔLE - (MGP)'), ('RESEAUX INFORMATIQUE ET TELECOMMUNICATION - (RIT)', 'RESEAUX INFORMATIQUE ET TELECOMMUNICATION - (RIT)'), ('SCIENCE ECONOMIQUE OPTION ECONOMIE - (SEG-ECO)', 'SCIENCE ECONOMIQUE OPTION ECONOMIE - (SEG-ECO)'), ('SCIENCE ECONOMIQUE OPTION GESTION - (SEG-GES)', 'SCIENCE ECONOMIQUE OPTION GESTION - (SEG-GES)'), (" SCIENCE DE L'INFORMATION ET DE LA COMMUNICATION - (SIC)", " SCIENCE DE L'INFORMATION ET DE LA COMMUNICATION - (SIC)"), ('SOCIOLOGIE ET ETHNOLOGIE - (SOC)', 'SOCIOLOGIE ET ETHNOLOGIE - (SOC)'), ('TOURISME HÔTELERIE - (TH)', 'TOURISME HÔTELERIE - (TH)'), ('TRANSPORT LOGISTIQUE - (TLOG)', 'TRANSPORT LOGISTIQUE - (TLOG)')], max_length=100)),
                ('cycle', models.CharField(choices=[('CYCLE PROFESSIONNEL', 'CYCLE PROFESSIONNEL'), ('CYCLE UNIVERSITAIRE', 'CYCLE UNIVERSITAIRE')], default='CYCLE UNIVERSITAIRE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('theme_memoire', models.CharField(max_length=255)),
                ('support_pdf', models.FileField(upload_to='Memoires/')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ESPECE', 'ESPECE'), ('WAVE_MONEY', 'WAVE MONEY')], max_length=20)),
                ('statut', models.BooleanField(default=False, verbose_name='statut')),
                ('reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='commission')),
                ('reference_paiement', models.CharField(max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('frais_impression', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'impression")),
                ('service_annexe', models.BooleanField(default=False, verbose_name='Service annexe')),
                ('frais_annexe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais annexe')),
                ('intitule_annexe', models.CharField(blank=True, choices=[('PAGE_DE_GARDE', 'PAGE DE GARDE 1.000fr'), ('PAGINATION_TABLE_MATIERE', 'PAGINATION (TABLE DE MATIERE) 1.500fr'), ('COMPLET', 'COMPLET [P,PDG,TDM] 2.500fr')], max_length=50, null=True, verbose_name='Intitulé du service annexe')),
                ('montant', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Montant total')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Utilisateurs.etudiant')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('Personnel', 'Personnel')], default='etudiant', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
